name             'ultradns_client'
maintainer       'Brent Walker'
maintainer_email 'brent.walker@ge.com'
license          'All rights reserved'
description      'Installs/Configures ultradns_client'
long_description 'Installs/Configures ultradns_client'
version          '0.1.0'
